# This workflow calls the master E2E workflow with custom variables
name: Elemental UI End-To-End tests with Rancher Manager

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: ui-e2e-tests-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: false

jobs:
  ui-e2e-k3s:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      cluster_name: cluster-k3s
      k8s_version_to_provision: v1.24.7+k3s1
      rancher_channel: latest
      rancher_version: 2.7.0-rc12
      runner: elemental-e2e-ci-runner-spot-x86-64-1
      test_type: ui